language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t itaytest/multi-docker -f ./client/Dockerfile.dev ./client
    
#run the tests
script:
    - docker run -e CI=true itaytest/multi-docker npm run test -- --coverage

after_success:
    - docker build -t itaytest/multi-client ./client
    - docker build -t itaytest/multi-nginx ./nginx
    - docker build -t itaytest/multi-worker ./worker
    - docker build -t itaytest/multi-server ./server

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # put the images in docker hub
    - docker push itaytest/multi-client
    - docker push itaytest/multi-nginx
    - docker push itaytest/multi-worker
    - docker push itaytest/multi-server
    
 deploy:
    provider: elasticbeanstalk
    region: eu-west-2
    app: MuldiDocker
    env: Muldidocker-env
    bucket_name: elasticbeanstalk-eu-west-2-826126725884
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY