version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
        - '9001:80'
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest' 
  api:
    depends_on:
        - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server
      #map local env with the container one
    volumes:
      #Skip this one, meaning dont map it
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
    #Skip this one, meaning dont map it
    - /app/node_modules
    - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
        build:
          dockerfile: Dockerfile.dev
          context: ./client
        volumes:
        #Skip this one, meaning dont map it
        - /app/node_modules
        - ./client:/app